In [1]:
import numpy as np

In [27]:
n=int(input())

def inp():
    b=list(map(float,input().split()))
    b=np.asarray(b)
    return b
points=[]
for i in range(n):
    k=inp()
    k=k.transpose()
    points.append(k)
print(points)
    

6
2 1
3 5
4 3
5 6
6 7
7 8
[array([2., 1.]), array([3., 5.]), array([4., 3.]), array([5., 6.]), array([6., 7.]), array([7., 8.])]


In [28]:
points[1][0]

3.0

In [29]:
c=np.reshape(points[0],(2,1))


In [30]:
c

array([[2.],
       [1.]])

In [31]:
x1=0
for i in range(n):
    x1+=points[i][0]
x2=0
for i in range(n):
    x2+=points[i][1]
mu=[]
mu.append(x1/n)
mu.append(x2/n)
print(mu)

[4.5, 5.0]


In [32]:
updated=[]
for i in range(n):
    updated.append(points[i]-mu)
updated

[array([-2.5, -4. ]),
 array([-1.5,  0. ]),
 array([-0.5, -2. ]),
 array([0.5, 1. ]),
 array([1.5, 2. ]),
 array([2.5, 3. ])]

In [33]:
x=updated[0]
x

array([-2.5, -4. ])

In [34]:
xt=np.reshape(updated[0],(2,1))

In [35]:
xt

array([[-2.5],
       [-4. ]])

In [36]:
m1=np.multiply(xt,x)
m1

array([[ 6.25, 10.  ],
       [10.  , 16.  ]])

In [37]:
m2=np.multiply(updated[1],(np.reshape(updated[1],(2,1))))
m2

array([[ 2.25, -0.  ],
       [-0.  ,  0.  ]])

In [38]:
m3=np.multiply(updated[2],(np.reshape(updated[2],(2,1))))
m3

array([[0.25, 1.  ],
       [1.  , 4.  ]])

In [39]:
m4=np.multiply(updated[3],(np.reshape(updated[3],(2,1))))
m4

array([[0.25, 0.5 ],
       [0.5 , 1.  ]])

In [40]:
m5=np.multiply(updated[4],(np.reshape(updated[4],(2,1))))
m5

array([[2.25, 3.  ],
       [3.  , 4.  ]])

In [41]:
m6=np.multiply(updated[5],(np.reshape(updated[5],(2,1))))
m6

array([[6.25, 7.5 ],
       [7.5 , 9.  ]])

In [42]:
cov=np.add(m6,np.add(m5,np.add(m4,np.add(m3,np.add(m2,m1)))))
cov

array([[17.5, 22. ],
       [22. , 34. ]])

In [43]:
cov=cov/n
cov

array([[2.91666667, 3.66666667],
       [3.66666667, 5.66666667]])

In [44]:
w,v=np.linalg.eig(cov)
print("Eigen values: ",w)

Eigen values:  [0.37566495 8.20766838]


In [46]:
print("Eigen Vectors: ",v)

Eigen Vectors:  [[-0.82192562 -0.56959484]
 [ 0.56959484 -0.82192562]]
