In [5]:
m,n=map(int,input().split())
A=[]
for i in range(m):
    row=[]
    for j in range(n):
        row.append(int(input()))
    A.append(row)
print(A)


2 3
3
1
1
-1
3
1
[[3, 1, 1], [-1, 3, 1]]


In [6]:
import numpy as np

In [11]:
AT=np.transpose(A)
AT

array([[ 3, -1],
       [ 1,  3],
       [ 1,  1]])

In [14]:
W=np.dot(A,AT)

In [15]:
val,vec=np.linalg.eig(W)

In [16]:
val

array([12., 10.])

In [17]:
vec

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [18]:
import math as m

In [39]:
vec.shape

(2, 2)

In [56]:
normx1=m.sqrt(vec[0][0]*vec[0][0]+vec[0][1]*vec[0][1])
normx1

0.9999999999999999

In [57]:
normx2=m.sqrt(vec[1][0]*vec[1][0]+vec[1][1]*vec[1][1])
normx2

0.9999999999999999

In [58]:
vec[0]=vec[0]/normx1
vec[0]

array([ 0.70710678, -0.70710678])

In [59]:
vec[1]=vec[1]/normx2
vec[1]

array([0.70710678, 0.70710678])

In [60]:
U=vec
U

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [73]:
A=[[3, 1, 1], [-1, 3, 1]]
A

[[3, 1, 1], [-1, 3, 1]]

In [74]:
import copy
sigma=copy.deepcopy(A)
sigma

[[3, 1, 1], [-1, 3, 1]]

In [75]:
for i in range(len(sigma)):
    for j in range(len(sigma[0])):
        if(i!=j):
            sigma[i][j]=0
sigma

[[3, 0, 0], [0, 3, 0]]

In [76]:
sigma[0][0]=m.sqrt(val[0])
sigma[1][1]=m.sqrt(val[1])
sigma

[[3.4641016151377544, 0, 0], [0, 3.1622776601683795, 0]]

In [77]:
A

[[3, 1, 1], [-1, 3, 1]]

In [78]:
AT=np.transpose(A)
AT

array([[ 3, -1],
       [ 1,  3],
       [ 1,  1]])

In [79]:
P=np.dot(AT,A)
P

array([[10,  0,  2],
       [ 0, 10,  4],
       [ 2,  4,  2]])

In [80]:
e_val,e_vec=np.linalg.eig(P)


In [81]:
e_val

array([ 0., 10., 12.])

In [82]:
e_vec

array([[ 1.82574186e-01, -8.94427191e-01, -4.08248290e-01],
       [ 3.65148372e-01,  4.47213595e-01, -8.16496581e-01],
       [-9.12870929e-01,  5.07704275e-16, -4.08248290e-01]])

In [83]:
normx1=m.sqrt(e_vec[0][0]*e_vec[0][0]+e_vec[0][1]*e_vec[0][1]+e_vec[0][2]*e_vec[0][2])
normx1

1.0

In [85]:
normx2=m.sqrt(e_vec[1][0]*e_vec[1][0]+e_vec[1][1]*e_vec[1][1]+e_vec[1][2]*e_vec[1][2])
normx3=m.sqrt(e_vec[2][0]*e_vec[2][0]+e_vec[2][1]*e_vec[2][1]+e_vec[2][2]*e_vec[2][2])
print(normx2)
print(normx3)

0.9999999999999998
1.0


In [86]:
e_vec[0]=e_vec[0]/normx1
e_vec[1]=e_vec[1]/normx2
e_vec[2]=e_vec[2]/normx3
e_vec

array([[ 1.82574186e-01, -8.94427191e-01, -4.08248290e-01],
       [ 3.65148372e-01,  4.47213595e-01, -8.16496581e-01],
       [-9.12870929e-01,  5.07704275e-16, -4.08248290e-01]])

In [87]:
V=np.transpose(e_vec)
V

array([[ 1.82574186e-01,  3.65148372e-01, -9.12870929e-01],
       [-8.94427191e-01,  4.47213595e-01,  5.07704275e-16],
       [-4.08248290e-01, -8.16496581e-01, -4.08248290e-01]])

In [88]:
res1=np.dot(U,sigma)
res1

array([[ 2.44948974, -2.23606798,  0.        ],
       [ 2.44948974,  2.23606798,  0.        ]])

In [90]:
final=np.dot(res1,V)
final

array([[ 2.4472136 , -0.10557281, -2.23606798],
       [-1.5527864 ,  1.89442719, -2.23606798]])